version: '3.8'
services:
  powerconsumption-db:
    image: postgres:latest
    ports:
      - "5437:5432"
    volumes:
      - ./powerconsumption-data:/var/lib/postgresql/data
    environment:
      - "POSTGRES_DB=power"
      - "POSTGRES_USER=timo"
      - "POSTGRES_PASSWORD=1234"