spring:
  application:
    name: powerconsumption
  datasource:
    password: 1234
    username: timo
    url: jdbc:postgresql://localhost:5437/power
server:
  port: 7080
provider:
  url: ${PROVIDER_URL}
verbrauch:
  cpu:
    min: 42
    max: 87
  gpu:
    min: 25
    max: 180
  aio: 10
  monitor: 50